# .github/scripts/kb/chunking-policy.yml
defaults:
  max_chars: 2400
  overlap: 300
  heading_aware: true
  preserve_code_fences: true

rules:
  - path_glob: "kb/hpcc4j/issues/**/*.md"
    max_chars: 2600
    overlap: 280
    respect_front_matter: true

  - path_glob: "kb/hpcc4j/wiki/**/*.md"
    max_chars: 2000
    overlap: 300
    heading_aware: true

  - path_glob: "kb/hpcc4j/project-docs/**/*.md"
    max_chars: 2400
    overlap: 300
    heading_aware: true

  - path_glob: "kb/hpcc4j/spark-hpcc-connector/**/*.md"
    max_chars: 2400
    overlap: 320
    preserve_code_fences: true

  - path_glob: "kb/hpcc4j/**/*.md"
    max_chars: 2400
    overlap: 300