name: K8s Regression Suite

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"

  workflow_dispatch:

jobs:
  test-against-platform:
    runs-on: ubuntu-latest

    steps:

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: PWD
      run: pwd

    - name: LS
      run: ls -rfv
      
    - name: Build commons-hpcc with Maven
      run: mvn -f ../commons-hpcc/pom.xml -B --activate-profiles jenkins-on-demand -Dmaven.gpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=false -Dhpccconn=https://eclwatch.default:8010 -Dwssqlconn=https://sql2ecl.default:8510 -DHPCC30117=open  install

    - name: Build wsclient with Maven
      run: mvn -f wsclient/pom.xml -B --activate-profiles jenkins-on-demand -Dmaven.gpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=false -Dhpccconn=https://eclwatch.default:8010 -Dwssqlconn=https://sql2ecl.default:8510 -DHPCC30117=open  install

    - name: Build dfsclient with Maven
      run: mvn -f dfsclient/pom.xml -B --activate-profiles jenkins-on-demand -Dmaven.gpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=false -Dhpccconn=https://eclwatch.default:8010 -Dwssqlconn=https://sql2ecl.default:8510 -DHPCC30117=open  install
